### PR TITLE
Battery Energy In & Out sensors for display on energy dashboard

### PR DESCRIPTION
**Pull request by purcell-lab**
This PR includes Battery Energy In/ Out sensors and corrects the Measurement class to allow display on the energy dashboard.

### CODE REVIEW

**Comment by purcell-lab** [comment]
This should address #19

**Comment by purcell-lab** [comment]
not quite ready for release.

Somedays I get beautiful curves:

image

Other days I get huge glitches if I reboot HA.

image

What I suspect is happening is on reboot I get a glitch in the battery in/out counters which then throws out the energy dashboard.

image

Somehow I need to check if it is available and only record those values, and ensure I don't get these zero values into the counter, using something like the [Availability Template](https://www.home-assistant.io/integrations/template/#availability)

**Review by hif2k1 — APPROVED** [review]
Thanks, exciting to have another contributor to the project.

**Comment by klaaspiet** [comment]
i got this problem to. is there a way to solve this?

**Comment by hif2k1** [comment]
Ok, thanks for letting me know, but this chain is a pull request that has been closed. Can you start a new issue and explain exactly what happens? Is it just on restart or randomly? Are there any error logs? Can you post any graphs or logs? Many thanks

**Pull request merged**
